---
title: "Untitled"
author: "Victoria Zaitceva"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

insurance_data <- read.csv("https://vincentarelbundock.github.io/Rdatasets/csv/AER/HealthInsurance.csv")
```


```{r}
glimpse(insurance_data)
```

```{r}

insurance_data <- insurance_data |>
  mutate(across(where(is.character), as.factor))

```

```{r}
summary(insurance_data)
```


```{r}
# create age groups

insurance_data <- insurance_data |>
  mutate(age_group = case_when(
    age >= 18 & age < 25 ~ "18 - 25",
    age >= 25 & age < 35 ~ "25 - 35",
    age >= 35 & age < 45 ~ "35 - 45",
    age >= 45 & age < 55 ~ "45 - 55",
    age >= 55  ~ "55 - 62",
  ),
  age_group = as.factor(age_group)) 

```



```{r}

insurance_data_long1 <- insurance_data |>
  pivot_longer(cols = c(age_group, health, gender, limit), 
               names_to = "variable", values_to = "value")


insurance_data_long1 <- insurance_data_long1 |>
  group_by(variable, value, insurance) |>
  summarise(count = n(), .groups = "drop") |>
  group_by(variable, value) |>
  mutate(percentage = count / sum(count) * 100) |>
  ungroup()


facet_labels1 <- c(
  age_group = "Возрастная группа",
  limit = "Есть ли заболевания?\n (объективная оценка)",
  gender = "Пол",
  health = "Все ли в порядке со здоровьем?\n (субъективная оценка)"
)


#total_counts <- insurance_data_long1 |>
  #group_by(variable, value) |>
  #summarize(total_count = sum(count), .groups = "drop")



plot_insurance_data_long1 <-
  insurance_data_long1 |>
  ggplot(aes(x = value, y = count, fill = insurance)) +
  geom_bar(stat = "identity", position = "stack") + 
  geom_text(aes(label = ifelse(count > 600, paste0(round(percentage, 1), "%"), "")),
            position = position_stack(vjust = 0.5), color = "white", size = 4) +
  #geom_text(data = total_counts, aes(x = value, y = total_count, label = total_count), 
            #vjust = -0.4, color = "black", size = 3, inherit.aes = FALSE) + 
  labs(
       x = "",
       y = "Число респондентов",
       fill = "Медицинская \nстраховка") +
  facet_wrap(~ variable, scales = "free_x", labeller = labeller(variable = facet_labels1)) +
  scale_fill_manual(values = c("yes" = "navy", "no" = "lightblue"), labels = c("yes" = "да", "no" = "нет")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        strip.text = element_text(size = 11, face = "bold"),
        panel.grid = element_blank(),
        plot.title = element_blank()) +
  scale_y_continuous(breaks = seq(0, 8000, 1000))



plot_insurance_data_long1

ggsave("plot_insurance_data_long1.png", plot_insurance_data_long1, width = 12, height = 8, units = "in")

```




```{r}
insurance_data_long2 <- insurance_data |>
  pivot_longer(cols = c(region,
                        ethnicity, selfemp, education), 
               names_to = "variable", values_to = "value")



insurance_data_long2 <- insurance_data_long2 |>
  group_by(variable, value, insurance) |>
  summarise(count = n(), .groups = "drop") |>
  group_by(variable, value) |>
  mutate(percentage = count / sum(count) * 100) |>
  ungroup()


facet_labels2 <- c(
  region = "Регион",
  ethnicity = "Этническая группа",
  selfemp = "Самозанятость",
  education = "Уровень образования"
)


plot_insurance_data_long2 <- 
  insurance_data_long2 |>
  ggplot(aes(x = value, y = count, fill = insurance)) +
  geom_bar(stat = "identity", position = "stack") + 
  geom_text(aes(label = ifelse(count > 600, paste0(round(percentage, 1), "%"), "")),
            position = position_stack(vjust = 0.5), color = "white", size = 4) +
  labs(title = "",
       x = "",
       y = "Число респондентов",
       fill = "Медицинская \nстраховка") +
  scale_fill_manual(values = c("yes" = "navy", "no" = "lightblue"), labels = c("yes" = "да", "no" = "нет")) +
  facet_wrap(~ variable, scales = "free_x", labeller = labeller(variable = facet_labels2)) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        strip.text = element_text(size = 11, face = "bold"),
        panel.grid = element_blank(),
        plot.title = element_blank()) +
  scale_y_continuous(breaks = seq(0, 8000, 1000))


plot_insurance_data_long2

ggsave("plot_insurance_data_long2.png", plot_insurance_data_long2, width = 12, height = 8, units = "in")
```


married

```{r}
insurance_data_long3 <- insurance_data |>
  pivot_longer(cols = married, 
               names_to = "variable", values_to = "value")



insurance_data_long3 <- insurance_data_long3 |>
  group_by(variable, value, insurance) |>
  summarise(count = n(), .groups = "drop") |>
  group_by(variable, value) |>
  mutate(percentage = count / sum(count) * 100) |>
  ungroup()


facet_labels3 <- c(
  married = "Женат/Замужем"
)


plot_insurance_data_long3 <- 
  insurance_data_long3 |>
  ggplot(aes(x = value, y = count, fill = insurance)) +
  geom_bar(stat = "identity", position = "stack") + 
  geom_text(aes(label = ifelse(count > 600, paste0(round(percentage, 1), "%"), "")),
            position = position_stack(vjust = 0.5), color = "white", size = 5) +
  labs(title = "Женат/Замужем",
       x = "",
       y = "Число респондентов",
       fill = "Медицинская \nстраховка") +
  scale_fill_manual(values = c("yes" = "navy", "no" = "lightblue"), labels = c("yes" = "да", "no" = "нет")) +
  theme_bw() +
  theme(axis.text.x = element_text(hjust = 1, size = 15),
        panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5)) +
  scale_y_continuous(breaks = seq(0, 8000, 1000))


plot_insurance_data_long3

ggsave("plot_insurance_data_long3.png", plot_insurance_data_long3, width = 12, height = 8, units = "in")
```















# age

```{r}
medians_age <- insurance_data |> 
  pivot_longer(cols = age, names_to = "variable", values_to = "value") |>
  group_by(variable, insurance) |>
  summarize(median_value = median(value), .groups = "drop")


age_boxplot <-
  insurance_data |> 
  pivot_longer(cols = age) |>
  ggplot(aes(x = insurance, y = value, fill = insurance)) +
  geom_boxplot() +
  geom_text(data = medians_age, aes(x = insurance, y = median_value + 0.1 * median_value, 
                                label = round(median_value, 1)), 
            color = "white", size = 5) +
    scale_fill_manual(values = c("yes" = "navy", "no" = "lightblue")) +
  labs(title = "Распределение возраста по\n наличию медицинской страховки",
       x = "",
       y = "Количество лет") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(size = 15))


age_boxplot


ggsave("age_boxplot.png", age_boxplot, width = 5, height = 6, units = "in")
  
```



```{r}
t_test_result <- t.test(age ~ insurance, data = insurance_data)
t_test_result

```
```{r}
wilcox_test_result <- wilcox.test(family ~ insurance, data = insurance_data)
wilcox_test_result

```

```{r}
# Step 1: Create a contingency table
contingency_table <- table(insurance_data$insurance, insurance_data$selfemp)

# View the contingency table
print(contingency_table)

# Step 2: Perform the Chi-Square Test
chi_square_test <- chisq.test(contingency_table, B = 10000)

# Display the test results
chi_square_test

```

```{r}
table(insurance_data$selfemp)
```


```{r}

medians_family <- insurance_data |> 
  pivot_longer(cols = family, names_to = "variable", values_to = "value") |>
  group_by(variable, insurance) |>
  summarize(median_value = median(value), .groups = "drop")


outliers_family <- insurance_data |>
  group_by(insurance) |>
  summarize(
    Q1 = quantile(family, 0.25),
    Q3 = quantile(family, 0.75),
    IQR = Q3 - Q1
  ) |>
  right_join(insurance_data, by = "insurance") |>
  filter(family < (Q1 - 1.5 * IQR) | family > (Q3 + 1.5 * IQR)) |>
  select(insurance, family)


family_boxplot <-
  insurance_data |> 
  pivot_longer(cols = family) |>
  ggplot(aes(x = insurance, y = value, fill = insurance)) +
  geom_boxplot() +
  geom_text(data = medians_family, aes(x = insurance, y = median_value + 0.1 * median_value, 
                                label = round(median_value, 1)), 
            color = "white", size = 5) +
  geom_text(data = outliers_family, aes(x = insurance, y = family, label = family),
            color = "grey", size = 5, vjust = -0.5) + 
  scale_fill_manual(values = c("yes" = "navy", "no" = "lightblue")) +
  labs(title = "Распределение числа членов семьи\n по наличию медицинской страховки",
       x = "",
       y = "Количество членов семьи") +
  theme_bw() +
  theme(panel.grid = element_blank(),
        legend.position = "none",
        plot.title = element_text(hjust = 0.5),
        axis.text.x = element_text(size = 15))

family_boxplot

ggsave("family_boxplot.png", family_boxplot, width = 5, height = 6, units = "in")

```


```{r}

facet_labels4 <- c("yes" = "Есть МС", "no" = "Нет МС")

health_limit <-
  insurance_data |>
  ggplot(aes(x = health, fill = factor(limit))) +
  geom_bar(position = "fill") +
  facet_wrap(~ insurance, labeller = labeller(insurance = facet_labels4)) +
  labs(title = "Субъективная и объективная оценки\n здоровья по наличию МС",
       x = "Субъективная оценка",
       y = "Пропорция",
       fill = "Объективная оценка") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(values = c("yes" = "darkgreen", "no" = "lightgreen"), labels = c("yes" = "да", "no" = "нет")) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        strip.text = element_text(size = 11, face = "bold"),
        plot.title = element_text(hjust = 0.5, size = 25),
        axis.text.x = element_text(size = 12),
        axis.title.x = element_text(size = 15),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 15) 
  )

health_limit

ggsave("health_limit.png", health_limit, width = 12, height = 8, units = "in")

```


```{r}
insurance_data |>
  ggplot(aes(x = selfemp, fill = factor(limit))) +
  geom_bar(position = "fill") +
  facet_wrap(~ insurance, labeller = labeller(insurance = facet_labels4)) +
  labs(title = "Субъективная и объективная оценки\n здоровья по наличию МС",
       x = "Self-employed",
       y = "Пропорция",
       fill = "объективная оценка") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(values = c("yes" = "darkgreen", "no" = "lightgreen"), labels = c("yes" = "да", "no" = "нет")) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5))
```





```{r}
insurance_data |>
  ggplot(aes(x = health, fill = factor(gender))) +
  geom_bar(position = "fill") +
  facet_wrap(~ insurance, labeller = labeller(insurance = facet_labels4)) +
  labs(title = "Субъективная и объективная оценки\n здоровья по наличию МС",
       x = "Gender",
       y = "Пропорция",
       fill = "Субъективная оценка") +
  scale_y_continuous(labels = scales::percent_format()) +
  scale_fill_manual(values = c("female" = "blue", "male" = "pink"), labels = c("yes" = "да", "no" = "нет")) +
  theme_bw() +
  theme(panel.grid = element_blank(),
        plot.title = element_text(hjust = 0.5))
```

```{r}
library(ggplot2)
library(ggpubr)

# Define the custom theme
theme_custom <- theme_minimal() + 
  theme(axis.text.x = element_text(angle = 45, hjust = 0.5, size = 8),
        plot.title = element_text(size = 12, face = "bold"),
        panel.background = element_rect(fill = "white"),  # Белый фон панели
    plot.background = element_rect(fill = "white") )

# Define the variables and initialize the list to store plots
categorical_vars <- c("health", "limit", "gender", "insurance", "married", "selfemp")
plot_list <- vector("list", length(categorical_vars))

# Create each plot and store in plot_list using index
for (i in seq_along(categorical_vars)) {
  var <- categorical_vars[i]
  p <- ggplot(insurance_data, aes_string(x = var)) +
    geom_bar(fill = "steelblue", color = "black", alpha = 0.7) +
    labs(title = switch(var,
        health = "Cостояниe здоровья",
        limit = "Наличие ограничений",
        gender = "Пол",
        insurance = "Наличие медицинской страховки",
        married = "Семейное положение",
        selfemp = "Самозанятость",
        "Распределение по переменной"), 
         x = "Категория",
         y = "Частота") +
    scale_x_discrete(labels = switch(var,
      health = c("Здоров(-а)", "Есть проблемы со здоровьем"),
      limit = c("Да", "Нет"),
      gender = c("Мужской", "Женский"),
      insurance = c("Есть", "Нет"),
      married = c("Замужем/Женат", "Не замужем/Не женат"),
      selfemp = c("Самозанятый", "Не самозанятый"),
      NULL)) +
    theme_custom +
    theme(axis.text.x = element_text(angle = 0, hjust = 0.5),
          axis.y.title = element_blank(),
          panel.grid = element_blank())
  
  # Store the plot in the list
  plot_list[[i]] <- p
}

# Arrange the plots in a 2x3 grid using ggarrange
distrib <- ggarrange(plotlist = plot_list, ncol = 3, nrow = 2)
distrib

ggsave("distrib.png", distrib, width = 12, height = 8, units = "in")


```





